publish:
#  only:
#    - tags
  script:
    - yum install -y python-setuptools
    - python3.5 -mpip install -U pip setuptools
    - python3.5 setup.py register -r pypi
    - python3.5 setup.py sdist upload -r pypi
