publish:
  only:
    - tags
  script:
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3.5 get-pip.py
    - python3.5 -mpip install twine
    - python3.5 setup.py sdist
    - twine upload --username $TWINE_USERNAME --password $TWINE_PASSWORD dist/*
