publish:
#  only:
#    - tags
  script:
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3.5 get-pip.py
    - python3.5 -mpip install -U pip setuptools
    - python3.5 setup.py register -r pypi
    - python3.5 setup.py sdist upload -r pypi
